var numeroActual="0";var primerNumero=null;var operador=null;var esperandoNumero=false;var pantallaResultado=document.getElementById("resultado");var pantallaOperacion=document.getElementById("operacion");var contenedorHistorial=document.getElementById("historial");mostrarHistorial();
function agregarNumero(numero){if(numero==="."&&numeroActual.indexOf(".")!==-1&&esperandoNumero===false){return;}if(esperandoNumero===true){numeroActual=numero==="."?"0.":numero;esperandoNumero=false;}else{if(numeroActual==="0"&&numero!=="."){numeroActual=numero;}else{numeroActual=numeroActual+numero;}}actualizarPantalla();}
function seleccionarOperacion(nuevoOperador){if(operador!==null&&esperandoNumero===false){calcular();}primerNumero=parseFloat(numeroActual);operador=nuevoOperador;esperandoNumero=true;pantallaOperacion.textContent=numeroActual+" "+obtenerSimbolo(operador);}
function calcular(){if(primerNumero===null||operador===null){return;}var segundoNumero=parseFloat(numeroActual);var resultado;if(operador==="+"){resultado=primerNumero+segundoNumero;}else if(operador==="-"){resultado=primerNumero-segundoNumero;}else if(operador==="*"){resultado=primerNumero*segundoNumero;}else if(operador==="/"){if(segundoNumero===0){pantallaResultado.textContent="Error";pantallaOperacion.textContent="No se puede dividir entre cero";numeroActual="0";primerNumero=null;operador=null;esperandoNumero=true;return;}resultado=primerNumero/segundoNumero;}resultado=Math.round(resultado*100000000)/100000000;var textoOperacion=primerNumero+" "+obtenerSimbolo(operador)+" "+segundoNumero+" = "+resultado;pantallaOperacion.textContent=textoOperacion;numeroActual=resultado.toString();actualizarPantalla();guardarEnHistorial(textoOperacion);primerNumero=null;operador=null;esperandoNumero=true;}
function actualizarPantalla(){pantallaResultado.textContent=numeroActual;}
function limpiarTodo(){numeroActual="0";primerNumero=null;operador=null;esperandoNumero=false;pantallaOperacion.textContent="";actualizarPantalla();}
function borrarUltimo(){if(esperandoNumero===true){return;}numeroActual=numeroActual.length>1?numeroActual.substring(0,numeroActual.length-1):"0";actualizarPantalla();}
function obtenerSimbolo(operacion){if(operacion==="*"){return "×";}if(operacion==="/"){return "÷";}return operacion;}
function obtenerHistorial(){var datos=localStorage.getItem("historialCalculadora");if(datos===null){return [];}try{return JSON.parse(datos);}catch(error){return [];}}
function guardarEnHistorial(operacion){var historial=obtenerHistorial();historial.unshift(operacion);localStorage.setItem("historialCalculadora",JSON.stringify(historial));mostrarHistorial();}
function mostrarHistorial(){var historial=obtenerHistorial();contenedorHistorial.innerHTML="";if(historial.length===0){var vacio=document.createElement("div");vacio.className="historial-vacio";vacio.textContent="No hay operaciones todavía.";contenedorHistorial.appendChild(vacio);return;}var i;for(i=0;i<historial.length;i++){var elemento=document.createElement("div");elemento.className="item-historial";elemento.textContent=historial[i];contenedorHistorial.appendChild(elemento);}}
function eliminarHistorial(){var confirmar=confirm("¿Deseas eliminar todo el historial?");if(confirmar===true){localStorage.removeItem("historialCalculadora");mostrarHistorial();}}
